# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Works\python\SimplePrint\DesignWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DesignWindow(object):
    def setupUi(self, DesignWindow):
        DesignWindow.setObjectName("DesignWindow")
        DesignWindow.resize(800, 600)
        DesignWindow.setMinimumSize(QtCore.QSize(800, 600))
        DesignWindow.setIconSize(QtCore.QSize(32, 32))
        DesignWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralWidget = QtWidgets.QWidget(DesignWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAddItem = QtWidgets.QToolButton(self.groupBox)
        self.btnAddItem.setMinimumSize(QtCore.QSize(32, 32))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/add2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddItem.setIcon(icon)
        self.btnAddItem.setIconSize(QtCore.QSize(32, 32))
        self.btnAddItem.setAutoRaise(True)
        self.btnAddItem.setObjectName("btnAddItem")
        self.horizontalLayout.addWidget(self.btnAddItem)
        self.btnLoadJpg = QtWidgets.QToolButton(self.groupBox)
        self.btnLoadJpg.setMinimumSize(QtCore.QSize(32, 32))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/res/pict.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLoadJpg.setIcon(icon1)
        self.btnLoadJpg.setIconSize(QtCore.QSize(32, 32))
        self.btnLoadJpg.setAutoRaise(True)
        self.btnLoadJpg.setObjectName("btnLoadJpg")
        self.horizontalLayout.addWidget(self.btnLoadJpg)
        self.btnDelJpg = QtWidgets.QToolButton(self.groupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/res/pictdel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelJpg.setIcon(icon2)
        self.btnDelJpg.setIconSize(QtCore.QSize(30, 30))
        self.btnDelJpg.setAutoRaise(True)
        self.btnDelJpg.setObjectName("btnDelJpg")
        self.horizontalLayout.addWidget(self.btnDelJpg)
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.btnAlignLeft = QtWidgets.QToolButton(self.groupBox)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/res/aleft.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlignLeft.setIcon(icon3)
        self.btnAlignLeft.setIconSize(QtCore.QSize(30, 30))
        self.btnAlignLeft.setAutoRaise(True)
        self.btnAlignLeft.setObjectName("btnAlignLeft")
        self.horizontalLayout.addWidget(self.btnAlignLeft)
        self.btnAlignRight = QtWidgets.QToolButton(self.groupBox)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/res/aright.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlignRight.setIcon(icon4)
        self.btnAlignRight.setIconSize(QtCore.QSize(30, 30))
        self.btnAlignRight.setAutoRaise(True)
        self.btnAlignRight.setObjectName("btnAlignRight")
        self.horizontalLayout.addWidget(self.btnAlignRight)
        self.btnAlignTop = QtWidgets.QToolButton(self.groupBox)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/res/atop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlignTop.setIcon(icon5)
        self.btnAlignTop.setIconSize(QtCore.QSize(30, 30))
        self.btnAlignTop.setAutoRaise(True)
        self.btnAlignTop.setObjectName("btnAlignTop")
        self.horizontalLayout.addWidget(self.btnAlignTop)
        self.btnAlignBottom = QtWidgets.QToolButton(self.groupBox)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/res/abottom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlignBottom.setIcon(icon6)
        self.btnAlignBottom.setIconSize(QtCore.QSize(30, 30))
        self.btnAlignBottom.setAutoRaise(True)
        self.btnAlignBottom.setObjectName("btnAlignBottom")
        self.horizontalLayout.addWidget(self.btnAlignBottom)
        self.btnSameWidth = QtWidgets.QToolButton(self.groupBox)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/res/samewidth.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSameWidth.setIcon(icon7)
        self.btnSameWidth.setIconSize(QtCore.QSize(30, 30))
        self.btnSameWidth.setAutoRaise(True)
        self.btnSameWidth.setObjectName("btnSameWidth")
        self.horizontalLayout.addWidget(self.btnSameWidth)
        self.btnSameHeight = QtWidgets.QToolButton(self.groupBox)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/res/sameheight.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSameHeight.setIcon(icon8)
        self.btnSameHeight.setIconSize(QtCore.QSize(30, 30))
        self.btnSameHeight.setAutoRaise(True)
        self.btnSameHeight.setObjectName("btnSameHeight")
        self.horizontalLayout.addWidget(self.btnSameHeight)
        spacerItem = QtWidgets.QSpacerItem(332, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnNewModel = QtWidgets.QPushButton(self.groupBox)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/res/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNewModel.setIcon(icon9)
        self.btnNewModel.setFlat(False)
        self.btnNewModel.setObjectName("btnNewModel")
        self.horizontalLayout.addWidget(self.btnNewModel)
        self.btnSaveModel = QtWidgets.QPushButton(self.groupBox)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/res/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSaveModel.setIcon(icon10)
        self.btnSaveModel.setObjectName("btnSaveModel")
        self.horizontalLayout.addWidget(self.btnSaveModel)
        self.btnPreview = QtWidgets.QPushButton(self.groupBox)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/res/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPreview.setIcon(icon11)
        self.btnPreview.setObjectName("btnPreview")
        self.horizontalLayout.addWidget(self.btnPreview)
        self.btnCancel = QtWidgets.QPushButton(self.groupBox)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/res/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancel.setIcon(icon12)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout.addWidget(self.groupBox)
        self.scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 778, 508))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        DesignWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(DesignWindow)
        self.statusBar.setObjectName("statusBar")
        DesignWindow.setStatusBar(self.statusBar)

        self.retranslateUi(DesignWindow)
        QtCore.QMetaObject.connectSlotsByName(DesignWindow)

    def retranslateUi(self, DesignWindow):
        _translate = QtCore.QCoreApplication.translate
        DesignWindow.setWindowTitle(_translate("DesignWindow", "模板设计"))
        self.btnAddItem.setToolTip(_translate("DesignWindow", "新增字段"))
        self.btnAddItem.setText(_translate("DesignWindow", "..."))
        self.btnLoadJpg.setToolTip(_translate("DesignWindow", "导入背景图片"))
        self.btnLoadJpg.setText(_translate("DesignWindow", "..."))
        self.btnDelJpg.setToolTip(_translate("DesignWindow", "删除背景"))
        self.btnDelJpg.setText(_translate("DesignWindow", "..."))
        self.btnAlignLeft.setToolTip(_translate("DesignWindow", "字段左对齐"))
        self.btnAlignLeft.setText(_translate("DesignWindow", "..."))
        self.btnAlignRight.setToolTip(_translate("DesignWindow", "字段右对齐"))
        self.btnAlignRight.setText(_translate("DesignWindow", "..."))
        self.btnAlignTop.setToolTip(_translate("DesignWindow", "字段上边对齐"))
        self.btnAlignTop.setText(_translate("DesignWindow", "..."))
        self.btnAlignBottom.setToolTip(_translate("DesignWindow", "字段下边对齐"))
        self.btnAlignBottom.setText(_translate("DesignWindow", "..."))
        self.btnSameWidth.setToolTip(_translate("DesignWindow", "字段设置相同宽度"))
        self.btnSameWidth.setText(_translate("DesignWindow", "..."))
        self.btnSameHeight.setToolTip(_translate("DesignWindow", "字段设置相同高度"))
        self.btnSameHeight.setText(_translate("DesignWindow", "..."))
        self.btnNewModel.setText(_translate("DesignWindow", "新建"))
        self.btnSaveModel.setText(_translate("DesignWindow", "保存"))
        self.btnPreview.setText(_translate("DesignWindow", "测试"))
        self.btnCancel.setText(_translate("DesignWindow", "退出"))

import printres_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DesignWindow = QtWidgets.QMainWindow()
    ui = Ui_DesignWindow()
    ui.setupUi(DesignWindow)
    DesignWindow.show()
    sys.exit(app.exec_())

