# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ItemProperty.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ItemProperty(object):
    def setupUi(self, ItemProperty):
        ItemProperty.setObjectName("ItemProperty")
        ItemProperty.resize(400, 450)
        ItemProperty.setMinimumSize(QtCore.QSize(400, 450))
        ItemProperty.setMaximumSize(QtCore.QSize(400, 450))
        ItemProperty.setSizeGripEnabled(True)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(ItemProperty)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.labelItemType = QtWidgets.QLabel(ItemProperty)
        self.labelItemType.setObjectName("labelItemType")
        self.horizontalLayout_11.addWidget(self.labelItemType)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.bMajor = QtWidgets.QCheckBox(ItemProperty)
        self.bMajor.setObjectName("bMajor")
        self.horizontalLayout_11.addWidget(self.bMajor)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.listEditType = QtWidgets.QListWidget(ItemProperty)
        self.listEditType.setObjectName("listEditType")
        self.verticalLayout_4.addWidget(self.listEditType)
        self.horizontalLayout_15.addLayout(self.verticalLayout_4)
        self.groupBox_2 = QtWidgets.QGroupBox(ItemProperty)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rbHLeft = QtWidgets.QRadioButton(self.groupBox_3)
        self.rbHLeft.setObjectName("rbHLeft")
        self.verticalLayout_2.addWidget(self.rbHLeft)
        self.rbHCenter = QtWidgets.QRadioButton(self.groupBox_3)
        self.rbHCenter.setObjectName("rbHCenter")
        self.verticalLayout_2.addWidget(self.rbHCenter)
        self.rbHRight = QtWidgets.QRadioButton(self.groupBox_3)
        self.rbHRight.setObjectName("rbHRight")
        self.verticalLayout_2.addWidget(self.rbHRight)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.horizontalLayout_9.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rbVTop = QtWidgets.QRadioButton(self.groupBox_4)
        self.rbVTop.setObjectName("rbVTop")
        self.verticalLayout_3.addWidget(self.rbVTop)
        self.rbVCenter = QtWidgets.QRadioButton(self.groupBox_4)
        self.rbVCenter.setObjectName("rbVCenter")
        self.verticalLayout_3.addWidget(self.rbVCenter)
        self.rbVBottom = QtWidgets.QRadioButton(self.groupBox_4)
        self.rbVBottom.setObjectName("rbVBottom")
        self.verticalLayout_3.addWidget(self.rbVBottom)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.horizontalLayout_9.addWidget(self.groupBox_4)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_15.addWidget(self.groupBox_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.groupBox = QtWidgets.QGroupBox(ItemProperty)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbTrim = QtWidgets.QCheckBox(self.groupBox)
        self.cbTrim.setObjectName("cbTrim")
        self.verticalLayout.addWidget(self.cbTrim)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbPrefix = QtWidgets.QCheckBox(self.groupBox)
        self.cbPrefix.setMinimumSize(QtCore.QSize(100, 0))
        self.cbPrefix.setObjectName("cbPrefix")
        self.horizontalLayout.addWidget(self.cbPrefix)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cPrefixText = QtWidgets.QLineEdit(self.groupBox)
        self.cPrefixText.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cPrefixText.setObjectName("cPrefixText")
        self.horizontalLayout.addWidget(self.cPrefixText)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbPostfix = QtWidgets.QCheckBox(self.groupBox)
        self.cbPostfix.setMinimumSize(QtCore.QSize(100, 0))
        self.cbPostfix.setObjectName("cbPostfix")
        self.horizontalLayout_2.addWidget(self.cbPostfix)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.cPostfixText = QtWidgets.QLineEdit(self.groupBox)
        self.cPostfixText.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cPostfixText.setObjectName("cPostfixText")
        self.horizontalLayout_2.addWidget(self.cPostfixText)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cbMeanCol = QtWidgets.QCheckBox(self.groupBox)
        self.cbMeanCol.setMinimumSize(QtCore.QSize(100, 0))
        self.cbMeanCol.setObjectName("cbMeanCol")
        self.horizontalLayout_3.addWidget(self.cbMeanCol)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.iMeanColVal = QtWidgets.QLineEdit(self.groupBox)
        self.iMeanColVal.setMaximumSize(QtCore.QSize(50, 16777215))
        self.iMeanColVal.setObjectName("iMeanColVal")
        self.horizontalLayout_3.addWidget(self.iMeanColVal)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cbPrintBorder = QtWidgets.QCheckBox(self.groupBox)
        self.cbPrintBorder.setMinimumSize(QtCore.QSize(100, 0))
        self.cbPrintBorder.setObjectName("cbPrintBorder")
        self.horizontalLayout_4.addWidget(self.cbPrintBorder)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.cbLineWrap = QtWidgets.QCheckBox(self.groupBox)
        self.cbLineWrap.setObjectName("cbLineWrap")
        self.horizontalLayout_4.addWidget(self.cbLineWrap)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.cCheckType = QtWidgets.QLineEdit(self.groupBox)
        self.cCheckType.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cCheckType.setObjectName("cCheckType")
        self.horizontalLayout_5.addWidget(self.cCheckType)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_5 = QtWidgets.QGroupBox(ItemProperty)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.textFont = QtWidgets.QLabel(self.groupBox_5)
        self.textFont.setObjectName("textFont")
        self.horizontalLayout_13.addWidget(self.textFont)
        self.btnFont = QtWidgets.QPushButton(self.groupBox_5)
        self.btnFont.setEnabled(True)
        self.btnFont.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btnFont.setObjectName("btnFont")
        self.horizontalLayout_13.addWidget(self.btnFont)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem11)
        self.btnOK = QtWidgets.QPushButton(ItemProperty)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout_12.addWidget(self.btnOK)
        self.btnCancel = QtWidgets.QPushButton(ItemProperty)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_12.addWidget(self.btnCancel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_16.addLayout(self.verticalLayout_5)

        self.retranslateUi(ItemProperty)
        self.btnCancel.clicked.connect(ItemProperty.reject)
        QtCore.QMetaObject.connectSlotsByName(ItemProperty)

    def retranslateUi(self, ItemProperty):
        _translate = QtCore.QCoreApplication.translate
        ItemProperty.setWindowTitle(_translate("ItemProperty", "属性修改"))
        self.labelItemType.setText(_translate("ItemProperty", "字段类型："))
        self.bMajor.setText(_translate("ItemProperty", "重要字段"))
        self.groupBox_2.setTitle(_translate("ItemProperty", "对齐方式"))
        self.groupBox_3.setTitle(_translate("ItemProperty", "左右对齐："))
        self.rbHLeft.setText(_translate("ItemProperty", "左对齐"))
        self.rbHCenter.setText(_translate("ItemProperty", "中对齐"))
        self.rbHRight.setText(_translate("ItemProperty", "右对齐"))
        self.groupBox_4.setTitle(_translate("ItemProperty", "上下对齐："))
        self.rbVTop.setText(_translate("ItemProperty", "上对齐"))
        self.rbVCenter.setText(_translate("ItemProperty", "中对齐"))
        self.rbVBottom.setText(_translate("ItemProperty", "下对齐"))
        self.groupBox.setTitle(_translate("ItemProperty", "字段选项"))
        self.cbTrim.setText(_translate("ItemProperty", "是否要删除首尾空格"))
        self.cbPrefix.setText(_translate("ItemProperty", "是否有前缀"))
        self.label.setText(_translate("ItemProperty", "字符"))
        self.cbPostfix.setText(_translate("ItemProperty", "是否有后缀"))
        self.label_2.setText(_translate("ItemProperty", "字符"))
        self.cbMeanCol.setText(_translate("ItemProperty", "是否均列打印"))
        self.label_3.setText(_translate("ItemProperty", "间隔"))
        self.iMeanColVal.setInputMask(_translate("ItemProperty", "99"))
        self.cbPrintBorder.setText(_translate("ItemProperty", "是否打印边框"))
        self.cbLineWrap.setText(_translate("ItemProperty", "是否折行打印"))
        self.label_4.setText(_translate("ItemProperty", "打勾项打印字符"))
        self.groupBox_5.setTitle(_translate("ItemProperty", "字体"))
        self.textFont.setText(_translate("ItemProperty", "TextLabel"))
        self.btnFont.setText(_translate("ItemProperty", "..."))
        self.btnOK.setText(_translate("ItemProperty", "确定"))
        self.btnCancel.setText(_translate("ItemProperty", "取消"))

