# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Works\python\SimplePrint\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnModType = QtWidgets.QPushButton(self.groupBox)
        self.btnModType.setMouseTracking(False)
        self.btnModType.setTabletTracking(False)
        self.btnModType.setCheckable(False)
        self.btnModType.setAutoRepeat(False)
        self.btnModType.setAutoExclusive(False)
        self.btnModType.setObjectName("btnModType")
        self.horizontalLayout.addWidget(self.btnModType)
        self.btnModLoad = QtWidgets.QPushButton(self.groupBox)
        self.btnModLoad.setObjectName("btnModLoad")
        self.horizontalLayout.addWidget(self.btnModLoad)
        self.btnModExp = QtWidgets.QPushButton(self.groupBox)
        self.btnModExp.setFlat(False)
        self.btnModExp.setObjectName("btnModExp")
        self.horizontalLayout.addWidget(self.btnModExp)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnModNew = QtWidgets.QPushButton(self.groupBox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnModNew.setIcon(icon)
        self.btnModNew.setObjectName("btnModNew")
        self.horizontalLayout_2.addWidget(self.btnModNew)
        self.btnModModi = QtWidgets.QPushButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/res/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnModModi.setIcon(icon1)
        self.btnModModi.setObjectName("btnModModi")
        self.horizontalLayout_2.addWidget(self.btnModModi)
        self.btnModDel = QtWidgets.QPushButton(self.groupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/res/del.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnModDel.setIcon(icon2)
        self.btnModDel.setObjectName("btnModDel")
        self.horizontalLayout_2.addWidget(self.btnModDel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEditQuery = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditQuery.setObjectName("lineEditQuery")
        self.horizontalLayout_3.addWidget(self.lineEditQuery)
        self.btnQuery = QtWidgets.QToolButton(self.groupBox)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("res/query.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnQuery.setIcon(icon3)
        self.btnQuery.setObjectName("btnQuery")
        self.horizontalLayout_3.addWidget(self.btnQuery)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.treeWidget = QtWidgets.QTreeWidget(self.groupBox)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.treeWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnPrintSingle = QtWidgets.QToolButton(self.groupBox_2)
        self.btnPrintSingle.setMinimumSize(QtCore.QSize(64, 64))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/res/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrintSingle.setIcon(icon4)
        self.btnPrintSingle.setIconSize(QtCore.QSize(32, 32))
        self.btnPrintSingle.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnPrintSingle.setAutoRaise(True)
        self.btnPrintSingle.setObjectName("btnPrintSingle")
        self.horizontalLayout_4.addWidget(self.btnPrintSingle)
        self.btnPrintNewData = QtWidgets.QToolButton(self.groupBox_2)
        self.btnPrintNewData.setMinimumSize(QtCore.QSize(64, 64))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/res/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrintNewData.setIcon(icon5)
        self.btnPrintNewData.setIconSize(QtCore.QSize(32, 32))
        self.btnPrintNewData.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnPrintNewData.setAutoRaise(True)
        self.btnPrintNewData.setObjectName("btnPrintNewData")
        self.horizontalLayout_4.addWidget(self.btnPrintNewData)
        self.btnPrintSaveData = QtWidgets.QToolButton(self.groupBox_2)
        self.btnPrintSaveData.setMinimumSize(QtCore.QSize(64, 64))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/res/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrintSaveData.setIcon(icon6)
        self.btnPrintSaveData.setIconSize(QtCore.QSize(32, 32))
        self.btnPrintSaveData.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnPrintSaveData.setAutoRaise(True)
        self.btnPrintSaveData.setObjectName("btnPrintSaveData")
        self.horizontalLayout_4.addWidget(self.btnPrintSaveData)
        self.btnPrintDatas = QtWidgets.QToolButton(self.groupBox_2)
        self.btnPrintDatas.setMinimumSize(QtCore.QSize(64, 64))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/res/custom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrintDatas.setIcon(icon7)
        self.btnPrintDatas.setIconSize(QtCore.QSize(32, 32))
        self.btnPrintDatas.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnPrintDatas.setAutoRaise(True)
        self.btnPrintDatas.setObjectName("btnPrintDatas")
        self.horizontalLayout_4.addWidget(self.btnPrintDatas)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.btnBatchPrint = QtWidgets.QToolButton(self.groupBox_2)
        self.btnBatchPrint.setMinimumSize(QtCore.QSize(64, 64))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/res/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBatchPrint.setIcon(icon8)
        self.btnBatchPrint.setIconSize(QtCore.QSize(32, 32))
        self.btnBatchPrint.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnBatchPrint.setAutoRaise(True)
        self.btnBatchPrint.setObjectName("btnBatchPrint")
        self.horizontalLayout_4.addWidget(self.btnBatchPrint)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_4.addWidget(self.line_2)
        self.btnPrintSetup = QtWidgets.QToolButton(self.groupBox_2)
        self.btnPrintSetup.setMinimumSize(QtCore.QSize(64, 64))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/res/setup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrintSetup.setIcon(icon9)
        self.btnPrintSetup.setIconSize(QtCore.QSize(32, 32))
        self.btnPrintSetup.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnPrintSetup.setAutoRaise(True)
        self.btnPrintSetup.setObjectName("btnPrintSetup")
        self.horizontalLayout_4.addWidget(self.btnPrintSetup)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 520, 441))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_4 = QtWidgets.QMenu(self.menu)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/res/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_4.setIcon(icon10)
        self.menu_4.setObjectName("menu_4")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setTabletTracking(False)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/res/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon11)
        self.actionExit.setObjectName("actionExit")
        self.actionsysbackup = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/res/approve.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsysbackup.setIcon(icon12)
        self.actionsysbackup.setObjectName("actionsysbackup")
        self.actionsysrestore = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/res/convert.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsysrestore.setIcon(icon13)
        self.actionsysrestore.setObjectName("actionsysrestore")
        self.actionprintsetup = QtWidgets.QAction(MainWindow)
        self.actionprintsetup.setIcon(icon9)
        self.actionprintsetup.setObjectName("actionprintsetup")
        self.actionsystemsetup = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("res/setup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsystemsetup.setIcon(icon14)
        self.actionsystemsetup.setObjectName("actionsystemsetup")
        self.actionhelp = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/res/option.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionhelp.setIcon(icon15)
        self.actionhelp.setObjectName("actionhelp")
        self.actionabout = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/res/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionabout.setIcon(icon16)
        self.actionabout.setObjectName("actionabout")
        self.actionmodload = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/res/preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionmodload.setIcon(icon17)
        self.actionmodload.setObjectName("actionmodload")
        self.actionmodexport = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/res/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionmodexport.setIcon(icon18)
        self.actionmodexport.setObjectName("actionmodexport")
        self.actiongenggai = QtWidgets.QAction(MainWindow)
        self.actiongenggai.setObjectName("actiongenggai")
        self.actionshanchu = QtWidgets.QAction(MainWindow)
        self.actionshanchu.setObjectName("actionshanchu")
        self.actionprintdatas = QtWidgets.QAction(MainWindow)
        self.actionprintdatas.setIcon(icon7)
        self.actionprintdatas.setObjectName("actionprintdatas")
        self.actioninfodatas = QtWidgets.QAction(MainWindow)
        self.actioninfodatas.setIcon(icon1)
        self.actioninfodatas.setObjectName("actioninfodatas")
        self.actionmenuType = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("res/document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionmenuType.setIcon(icon19)
        self.actionmenuType.setObjectName("actionmenuType")
        self.actionmenuTypeRename = QtWidgets.QAction(MainWindow)
        self.actionmenuTypeRename.setObjectName("actionmenuTypeRename")
        self.actionmenuTypeDelete = QtWidgets.QAction(MainWindow)
        self.actionmenuTypeDelete.setObjectName("actionmenuTypeDelete")
        self.actionmenuModNew = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("res/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionmenuModNew.setIcon(icon20)
        self.actionmenuModNew.setObjectName("actionmenuModNew")
        self.actionmenuModModify = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("res/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionmenuModModify.setIcon(icon21)
        self.actionmenuModModify.setObjectName("actionmenuModModify")
        self.actionmenuModDelete = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("res/del.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionmenuModDelete.setIcon(icon22)
        self.actionmenuModDelete.setObjectName("actionmenuModDelete")
        self.actionsyssetup = QtWidgets.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/res/address.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsyssetup.setIcon(icon23)
        self.actionsyssetup.setObjectName("actionsyssetup")
        self.menu_4.addAction(self.actionmenuType)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.actionmenuModNew)
        self.menu_4.addAction(self.actionmenuModModify)
        self.menu_4.addAction(self.actionmenuModDelete)
        self.menu.addAction(self.menu_4.menuAction())
        self.menu.addAction(self.actionprintdatas)
        self.menu.addSeparator()
        self.menu.addAction(self.actionmodload)
        self.menu.addAction(self.actionmodexport)
        self.menu.addSeparator()
        self.menu.addAction(self.actionExit)
        self.menu_2.addAction(self.actionprintsetup)
        self.menu_3.addAction(self.actionhelp)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.actionabout)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "套打助手"))
        self.groupBox.setTitle(_translate("MainWindow", "模板管理"))
        self.btnModType.setToolTip(_translate("MainWindow", "管理模板类别"))
        self.btnModType.setText(_translate("MainWindow", "类别管理"))
        self.btnModLoad.setToolTip(_translate("MainWindow", "导入外部模板"))
        self.btnModLoad.setText(_translate("MainWindow", "导入模板"))
        self.btnModExp.setToolTip(_translate("MainWindow", "将当前模板导出为独立模板文件"))
        self.btnModExp.setText(_translate("MainWindow", "导出模板"))
        self.btnModNew.setToolTip(_translate("MainWindow", "新建模板"))
        self.btnModNew.setText(_translate("MainWindow", "新建"))
        self.btnModModi.setToolTip(_translate("MainWindow", "更改当前模板"))
        self.btnModModi.setText(_translate("MainWindow", "更改"))
        self.btnModDel.setToolTip(_translate("MainWindow", "删除当前模板"))
        self.btnModDel.setText(_translate("MainWindow", "删除"))
        self.label.setText(_translate("MainWindow", "查找："))
        self.btnQuery.setText(_translate("MainWindow", "查"))
        self.btnPrintSingle.setToolTip(_translate("MainWindow", "打印当前票据"))
        self.btnPrintSingle.setText(_translate("MainWindow", "单张打印"))
        self.btnPrintNewData.setToolTip(_translate("MainWindow", "清空当前票据中的数据，重新录入"))
        self.btnPrintNewData.setText(_translate("MainWindow", "重新录入"))
        self.btnPrintSaveData.setToolTip(_translate("MainWindow", "保存当前票据到票据仓库中"))
        self.btnPrintSaveData.setText(_translate("MainWindow", "保存票据"))
        self.btnPrintDatas.setToolTip(_translate("MainWindow", "从票据仓库中读入到当前票据"))
        self.btnPrintDatas.setText(_translate("MainWindow", "票据仓库"))
        self.btnBatchPrint.setToolTip(_translate("MainWindow", "根据批量数据文件打印多张凭证"))
        self.btnBatchPrint.setText(_translate("MainWindow", "批量打印"))
        self.btnPrintSetup.setToolTip(_translate("MainWindow", "设置打印机参数"))
        self.btnPrintSetup.setText(_translate("MainWindow", "打印设置"))
        self.menu.setTitle(_translate("MainWindow", "系统"))
        self.menu_4.setTitle(_translate("MainWindow", "模板管理"))
        self.menu_2.setTitle(_translate("MainWindow", "设置"))
        self.menu_3.setTitle(_translate("MainWindow", "帮助"))
        self.action_3.setText(_translate("MainWindow", "打印机设置"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionsysbackup.setText(_translate("MainWindow", "系统备份"))
        self.actionsysrestore.setText(_translate("MainWindow", "系统恢复"))
        self.actionprintsetup.setText(_translate("MainWindow", "打印设置"))
        self.actionsystemsetup.setText(_translate("MainWindow", "系统参数"))
        self.actionhelp.setText(_translate("MainWindow", "帮助"))
        self.actionabout.setText(_translate("MainWindow", "关于 ..."))
        self.actionmodload.setText(_translate("MainWindow", "导入模板"))
        self.actionmodexport.setText(_translate("MainWindow", "导出模板"))
        self.actiongenggai.setText(_translate("MainWindow", "更改模板"))
        self.actionshanchu.setText(_translate("MainWindow", "shanchu "))
        self.actionprintdatas.setText(_translate("MainWindow", "票据仓库"))
        self.actioninfodatas.setText(_translate("MainWindow", "备选信息"))
        self.actionmenuType.setText(_translate("MainWindow", "类别管理"))
        self.actionmenuTypeRename.setText(_translate("MainWindow", "类别重命名"))
        self.actionmenuTypeDelete.setText(_translate("MainWindow", "删除类别"))
        self.actionmenuModNew.setText(_translate("MainWindow", "新建模板"))
        self.actionmenuModModify.setText(_translate("MainWindow", "更改模板"))
        self.actionmenuModDelete.setText(_translate("MainWindow", "删除模板"))
        self.actionsyssetup.setText(_translate("MainWindow", "系统参数"))

import printres_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

