# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Works\python\SimplePrint\NewVoucherDlg.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewVoucherDlg(object):
    def setupUi(self, NewVoucherDlg):
        NewVoucherDlg.setObjectName("NewVoucherDlg")
        NewVoucherDlg.resize(357, 203)
        NewVoucherDlg.setSizeGripEnabled(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(NewVoucherDlg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(NewVoucherDlg)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.edtName = QtWidgets.QLineEdit(self.groupBox)
        self.edtName.setObjectName("edtName")
        self.horizontalLayout.addWidget(self.edtName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.edtDisplayText = QtWidgets.QLineEdit(self.groupBox)
        self.edtDisplayText.setObjectName("edtDisplayText")
        self.horizontalLayout_6.addWidget(self.edtDisplayText)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.cmbType = QtWidgets.QComboBox(self.groupBox)
        self.cmbType.setMinimumSize(QtCore.QSize(150, 0))
        self.cmbType.setObjectName("cmbType")
        self.horizontalLayout_4.addWidget(self.cmbType)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.edtWidth = QtWidgets.QLineEdit(self.groupBox)
        self.edtWidth.setObjectName("edtWidth")
        self.horizontalLayout_2.addWidget(self.edtWidth)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.edtHeight = QtWidgets.QLineEdit(self.groupBox)
        self.edtHeight.setObjectName("edtHeight")
        self.horizontalLayout_3.addWidget(self.edtHeight)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(373, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.btnOK = QtWidgets.QPushButton(self.groupBox)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout_5.addWidget(self.btnOK)
        self.btnCancel = QtWidgets.QPushButton(self.groupBox)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_5.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(NewVoucherDlg)
        QtCore.QMetaObject.connectSlotsByName(NewVoucherDlg)

    def retranslateUi(self, NewVoucherDlg):
        _translate = QtCore.QCoreApplication.translate
        NewVoucherDlg.setWindowTitle(_translate("NewVoucherDlg", "新建凭证模板"))
        self.label.setText(_translate("NewVoucherDlg", "凭证名称："))
        self.label_7.setText(_translate("NewVoucherDlg", "显示名称："))
        self.label_6.setText(_translate("NewVoucherDlg", "凭证类别："))
        self.label_2.setText(_translate("NewVoucherDlg", "凭证宽度："))
        self.edtWidth.setInputMask(_translate("NewVoucherDlg", "000"))
        self.label_3.setText(_translate("NewVoucherDlg", "(毫米)"))
        self.label_4.setText(_translate("NewVoucherDlg", "凭证高度："))
        self.edtHeight.setInputMask(_translate("NewVoucherDlg", "000"))
        self.label_5.setText(_translate("NewVoucherDlg", "(毫米)"))
        self.btnOK.setText(_translate("NewVoucherDlg", "确认"))
        self.btnCancel.setText(_translate("NewVoucherDlg", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewVoucherDlg = QtWidgets.QDialog()
    ui = Ui_NewVoucherDlg()
    ui.setupUi(NewVoucherDlg)
    NewVoucherDlg.show()
    sys.exit(app.exec_())

