# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Works\Python\SimplePrint\PrintLogDlg.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PrintLogDlg(object):
    def setupUi(self, PrintLogDlg):
        PrintLogDlg.setObjectName("PrintLogDlg")
        PrintLogDlg.setWindowModality(QtCore.Qt.NonModal)
        PrintLogDlg.resize(705, 527)
        PrintLogDlg.setSizeGripEnabled(True)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(PrintLogDlg)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(PrintLogDlg)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.edtDate = QtWidgets.QLineEdit(PrintLogDlg)
        self.edtDate.setMinimumSize(QtCore.QSize(80, 0))
        self.edtDate.setMaximumSize(QtCore.QSize(80, 16777215))
        self.edtDate.setObjectName("edtDate")
        self.horizontalLayout.addWidget(self.edtDate)
        self.label_2 = QtWidgets.QLabel(PrintLogDlg)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.edtVoucherName = QtWidgets.QLineEdit(PrintLogDlg)
        self.edtVoucherName.setObjectName("edtVoucherName")
        self.horizontalLayout.addWidget(self.edtVoucherName)
        self.btnQuery = QtWidgets.QPushButton(PrintLogDlg)
        self.btnQuery.setObjectName("btnQuery")
        self.horizontalLayout.addWidget(self.btnQuery)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnClean = QtWidgets.QPushButton(PrintLogDlg)
        self.btnClean.setObjectName("btnClean")
        self.horizontalLayout.addWidget(self.btnClean)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tvLogDetails = QtWidgets.QTableView(PrintLogDlg)
        self.tvLogDetails.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tvLogDetails.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tvLogDetails.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tvLogDetails.setObjectName("tvLogDetails")
        self.verticalLayout.addWidget(self.tvLogDetails)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnFirst = QtWidgets.QToolButton(PrintLogDlg)
        self.btnFirst.setMinimumSize(QtCore.QSize(48, 0))
        self.btnFirst.setMaximumSize(QtCore.QSize(48, 20))
        self.btnFirst.setObjectName("btnFirst")
        self.horizontalLayout_2.addWidget(self.btnFirst)
        self.btnPrev = QtWidgets.QToolButton(PrintLogDlg)
        self.btnPrev.setMinimumSize(QtCore.QSize(48, 0))
        self.btnPrev.setMaximumSize(QtCore.QSize(48, 20))
        self.btnPrev.setObjectName("btnPrev")
        self.horizontalLayout_2.addWidget(self.btnPrev)
        self.btnNext = QtWidgets.QToolButton(PrintLogDlg)
        self.btnNext.setMinimumSize(QtCore.QSize(48, 0))
        self.btnNext.setMaximumSize(QtCore.QSize(48, 20))
        self.btnNext.setObjectName("btnNext")
        self.horizontalLayout_2.addWidget(self.btnNext)
        self.btnLast = QtWidgets.QToolButton(PrintLogDlg)
        self.btnLast.setMinimumSize(QtCore.QSize(48, 0))
        self.btnLast.setMaximumSize(QtCore.QSize(48, 20))
        self.btnLast.setObjectName("btnLast")
        self.horizontalLayout_2.addWidget(self.btnLast)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btnOK = QtWidgets.QPushButton(PrintLogDlg)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout_3.addWidget(self.btnOK)
        self.btnCancel = QtWidgets.QPushButton(PrintLogDlg)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_3.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)

        self.retranslateUi(PrintLogDlg)
        self.btnCancel.clicked.connect(PrintLogDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(PrintLogDlg)

    def retranslateUi(self, PrintLogDlg):
        _translate = QtCore.QCoreApplication.translate
        PrintLogDlg.setWindowTitle(_translate("PrintLogDlg", "打印数据仓库"))
        self.label.setText(_translate("PrintLogDlg", "打印日期(YYYY-MM-DD)："))
        self.edtDate.setInputMask(_translate("PrintLogDlg", "9999-99-99"))
        self.label_2.setText(_translate("PrintLogDlg", "凭证名称："))
        self.btnQuery.setText(_translate("PrintLogDlg", "查询"))
        self.btnClean.setText(_translate("PrintLogDlg", "清理日志"))
        self.btnFirst.setText(_translate("PrintLogDlg", "首页"))
        self.btnPrev.setText(_translate("PrintLogDlg", "上一页"))
        self.btnNext.setText(_translate("PrintLogDlg", "下一页"))
        self.btnLast.setText(_translate("PrintLogDlg", "末页"))
        self.btnOK.setText(_translate("PrintLogDlg", "选择"))
        self.btnCancel.setText(_translate("PrintLogDlg", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PrintLogDlg = QtWidgets.QDialog()
    ui = Ui_PrintLogDlg()
    ui.setupUi(PrintLogDlg)
    PrintLogDlg.show()
    sys.exit(app.exec_())

